/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorPicker: typeof import('./src/components/commands/ColorPicker.vue')['default']
    ColorPopover: typeof import('./src/components/commands/ColorPopover.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
